apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-express
  name: mongo-express
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30400
  selector:
    app: mongo-express
  type: NodePort
